BEGIN TRANSACTION;
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`id`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`username`	TEXT NOT NULL UNIQUE,
	`secret`	TEXT NOT NULL
);
DROP TABLE IF EXISTS `notes`;
CREATE TABLE `notes` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`from_user_id` INTEGER NOT NULL,
	`from_username` TEXT NOT NULL,
	`to_user_id` INTEGER NOT NULL,
	`note` TEXT
);
COMMIT;
